bbs/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'bbs'
urlpatterns = [
    # path('', views.bbs_list),
    # path('<int:pk>/', views.bbs_detail),

    path('', views.BbsList.as_view()),
    path('<int:pk>/', views.BbsDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

blog/urls.py
from django.urls import path, re_path
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # ex: /
    path('', views.PostLV.as_view(), name='index'),  # 1

    # ex: /post/ (same as /)
    path('post/', views.PostLV.as_view(), name='post_list'),  # 2

    # ex: /archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),  # 4

    # ex: /today/
    path('today/', views.PostTAV.as_view(), name='post_today_archive'),

    # ex: /post/slug/
    path('post/<slug:slug>/', views.PostDV.as_view(), name='post_detail'),  # 3
    # re_path('post/(?P<slug>[\w-_]+)/', views.PostDV.as_view(), name='post_detail'),  # 3

    # ex: /2017/nov/
    path('<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),  # 6

    # ex: /2017/nov/10/
    path('<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),  # 7

    # ex: /2017/
    path('<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),  # 5

    # ex: /tag/
    path('tag/', views.TagTV.as_view(), name='tag_cloud'),

    # ex: /tag/tagname/
    path('tag/<tag>/', views.PostTOL.as_view(), name='tagged_object_list'),

    # ex: /search/
    path('search/', views.SearchFormView.as_view(), name='search'),

    # ex: /add/
    path('add/', views.PostCreateView.as_view(), name="add"),

    # ex: /change/
    path('change/', views.PostChangeLV.as_view(), name="change"),

    # ex: /99/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update"),

    # ex: /99/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete"),
]

bookmark/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),


    path('add/', views.BookmarkCreateView.as_view(), name="add"),

    # ex: /change/
    path('change/', views.BookmarkChangeLV.as_view(), name="change"),

    # ex: /99/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update"),

    # ex: /99/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete"),

]

home/urls.py
from django.urls import path

from . import views

# urlpatterns = [
#     # ex: /polls/
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.IndexView.as_view(), name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    # path('rest_app/', include('rest_app.urls')),

    # path('ezp_api/', include('ezp_api.urls')),
    path('ezp10/', include('ezp10.urls')),
    path('gm_photos/', include('gm_photos.urls')),

    path('photo/', include('photo.urls')),
    path('blog/', include('blog.urls')),
    path('bbs/', include('bbs.urls')),
    path('memo/', include('memo.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('polls/', include('polls.urls')),
    path('feedback/', include('feedback.urls')),
    path('home/', include('home.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', views.UserCreateDoneTV.as_view(), name='register_done'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from . import views

app_name = 'photo'
urlpatterns = [
    # ex: /
    path('', views.AlbumLV.as_view(), name='index'),

    # ex: /album/, same as /
    path('album/', views.AlbumLV.as_view(), name='album_list'),

    # ex: /album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    # ex: /photo/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    # ex: /album/add/
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),

    # ex: /album/change/
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),

    # ex: /album/99/update/
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),

    # ex: /album/99/delete/
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),

    # ex: /photo/add/
    path('photo/add/', views.PhotoCreateView.as_view(), name='photo_add'),

    # ex: /photo/change/
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    # ex: /photo/99/update/
    path('photo/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),

    # ex: /photo/99/delete/
    path('photo/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


# Create your views here.
def index(request):
    msg = 'My Message...'
    return render(request, 'home/index.html', {'message': msg})

templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <title>{% block title %} Django Web Programming {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
</head>

<body>
<div id="header">
    <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>

    {% if user.is_active %}
    <h4 class="welcome">Welcome,
        <strong>{% firstof user.get_short_name user.get_username %}</strong>
        <a href="{% url 'password_change' %}">Change Password</a>
        <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">Welcome, Anonymous
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'photo:index' %}">Photo</a></li>
    <li><a href="#">Add&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:add' %}">Post</a></li>
            <li><a href="{% url 'photo:album_add' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
        </ul>
    </li>
    <li><a href="#">Change&bigtriangledown;</a>
        <ul>
            <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:change' %}">Post</a></li>
            <li><a href="{% url 'photo:album_change' %}">Album</a></li>
            <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
        </ul>
    </li>
    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
</body>
</html>

templates/fb_base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <title>My Web</title>

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <h2>
            My Web
        </h2>
    </div>

    <div class="container">
        {% block title %}
        {% endblock title %}
    </div>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static 'css/home.css' %}{% endblock %}

{% block content %}
<div id="content"_home>
    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
            <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="{% url 'bookmark:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'bookmark:change' %}">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="{% url 'blog:add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'blog:change' %}">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="#">Photo</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="{% url 'photo:album_add' %}">Add</a></i></td>
            <td class="Edit"><i><a href="{% url 'photo:photo_change' %}">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; makingfunk 2017
</div>
{% endblock footer %}

templates/layout.html
<!DOCTYPE html>
<html lang="ko">

{% load staticfiles %}

<head>
    <title>{% block page_title %}Pystagram{% endblock %}</title>
    <meta charset="utf-8">
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<body>
{% block content %}{% endblock %}
</body>

</html>